staging:
  secret_key_base: c0be691639ceda3ef2913a0fe0e399c055d583c53e0df4a3f86f1817acbd220d3c64e282fc9babdcabf997729775a650b8857202c7e22a52672110c94bf07738
production:
  secret_key_base: f29c51d9a4fcaf7f328f468ace7f93e10ac4a9b1080bd40e54cb2fdffa80
